<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<!--<Nullable>enable</Nullable>-->
		<Optimize>true</Optimize>
		<NoWarn>CS0649</NoWarn>
	  <IsPublishable>False</IsPublishable>
		
		<OutputPath>..\..\1.5\Assemblies\</OutputPath>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4297" ExcludeAssets="runtime" />
		<PackageReference Include="Lib.Harmony.Thin" Version="2.3.3" ExcludeAssets="runtime" />
		<PackageReference Include="UnlimitedHugs.Rimworld.HugsLib" Version="11.0.3" ExcludeAssets="runtime" />
		<PackageReference Include="RimWorld.MultiplayerAPI" Version="0.5.0" />
	</ItemGroup>

</Project>